#pragma once
#include <string>
#include <utility>
#include <vector>
// Dictionary of commonName:internalName, used to populate dropdown lists
const std::vector<std::pair<std::wstring, std::wstring>> ROOM_NAMES = {
    // Main 46 blue rooms
    {L"The Foundation", L"THE FOUNDATION" },
    {L"Entrance Hall", L"ENTRANCE HALL" },
    {L"Spare Room", L"SPARE ROOM" },
    {L"Rotunda", L"ROTUNDA" },
    {L"Parlor", L"PARLOR" },
    {L"Billiard Room", L"BILLIARD ROOM" },
    {L"Gallery", L"GALLERY" },
    {L"Room 8", L"ROOM 8" },
    {L"Closet", L"CLOSET" },
    {L"Walk-in Closet", L"WALK-IN CLOSET" },
    {L"Attic", L"ATTIC" },
    {L"Storeroom", L"STOREROOM" },
    {L"Nook", L"NOOK" },
    {L"Garage", L"GARAGE" },
    {L"Music Room", L"MUSIC ROOM" },
    {L"Locker Room", L"LOCKER ROOM" },
    {L"Den", L"DEN" },
    {L"Wine Cellar", L"WINE CELLAR" },
    {L"Trophy Room", L"TROPHY ROOM" },
    {L"Ballroom", L"BALLROOM" },
    {L"Pantry", L"PANTRY" },
    {L"Rumpus Room", L"RUMPUS ROOM" },
    {L"Vault", L"VAULT" },
    {L"Office", L"OFFICE" },
    {L"Drawing Room", L"DRAWING ROOM" },
    {L"Study", L"STUDY" },
    {L"Library", L"LIBRARY" },
    {L"Chamber of Mirrors", L"CHAMBER OF MIRRORS" },
    {L"The Pool", L"THE POOL" },
    {L"Drafting Studio", L"DRAFTING STUDIO" },
    {L"Utility Closet", L"UTILITY CLOSET" },
    {L"Boiler Room", L"BOILER ROOM" },
    {L"Pump Room", L"PUMP ROOM" },
    {L"Security", L"SECURITY" },
    {L"Workshop", L"WORKSHOP" },
    {L"Laboratory", L"LABORATORY" },
    {L"Sauna", L"SAUNA" },
    {L"Coat Check", L"COAT CHECK" },
    {L"Mail Room", L"MAIL ROOM" },
    {L"Freezer", L"FREEZER" },
    {L"Dining Room", L"DINING ROOM" },
    {L"Observatory", L"OBSERVATORY" },
    {L"Conference Room", L"CONFERENCE ROOM" },
    {L"Aquarium", L"AQUARIUM" },
    {L"Antechamber", L"ANTECHAMBER" },
    {L"Room 46", L"ROOM 46" },

    // Bedrooms
    {L"Bedroom", L"BEDROOM" },
    {L"Boudoir", L"BOUDOIR" },
    {L"Guest Bedroom", L"GUEST BEDROOM" },
    {L"Nursery", L"NURSERY" },
    {L"Servant's Quarters", L"SERVANT'S QUARTERS" },
    {L"Bunk Room", L"BUNK ROOM" },
    {L"Her Ladyship's Chamber", L"HER LADYSHIP'S CHAMBER" },
    {L"Master Bedroom", L"MASTER BEDROOM" },

    // Hallways
    {L"Hallway", L"HALLWAY" },
    {L"West Wing Hall", L"WEST WING HALL" },
    {L"East Wing Hall", L"EAST WING HALL" },
    {L"Corridor", L"CORRIDOR" },
    {L"Passageway", L"PASSAGEWAY" },
    {L"Secret Passage", L"SECRET PASSAGE" },
    {L"Foyer", L"FOYER" },
    {L"Great Hall", L"GREAT HALL" },

    // Green Rooms
    {L"Terrace", L"TERRACE" },
    {L"Patio", L"PATIO" },
    {L"Courtyard", L"COURTYARD" },
    {L"Cloister", L"CLOISTER" },
    {L"Veranda", L"VERANDA" },
    {L"Greenhouse", L"GREENHOUSE" },
    {L"Morning Room", L"MORNING ROOM" },
    {L"Secret Garden", L"SECRET GARDEN" },

    // Shops
    {L"Commissary", L"COMMISSARY" },
    {L"Kitchen", L"KITCHEN" },
    {L"Locksmith", L"LOCKSMITH" },
    {L"Showroom", L"SHOWROOM" },
    {L"Laundry room", L"LAUNDRY ROOM" },
    {L"Bookshop", L"BOOKSHOP" },
    {L"The Armory", L"THE ARMORY" },
    {L"Gift Shop", L"GIFT SHOP" },

    // Red Rooms
    {L"Lavatory", L"LAVATORY" },
    {L"Chapel", L"CHAPEL" },
    {L"Maid's Chamber", L"MAID'S CHAMBER" },
    {L"Archives", L"ARCHIVES" },
    {L"Gymnasium", L"GYMNASIUM" },
    {L"Darkroom", L"DARKROOM" },
    {L"Furnace", L"FURNACE" },
    {L"Weight Room", L"WEIGHT ROOM" },

    // Studio Additions
    {L"Dovecote", L"DOVECOTE" },
    {L"The Kennel", L"THE KENNEL" },
    {L"Clock Tower", L"CLOCK TOWER" },
    {L"Classroom", L"CLASSROOM" },
    {L"Solarium", L"SOLARIUM" },
    {L"Dormitory", L"DORMITORY" },
    {L"Vestibule", L"VESTIBULE" },
    {L"Casino", L"CASINO" },

    // Found Floorplans
    {L"Planetarium", L"PLANETARIUM" },
    {L"Mechanarium", L"MECHANARIUM" },
    {L"Treasure Trove", L"TREASURE TROVE" },
    {L"Throne Room", L"THRONE ROOM" },
    {L"Tunnel", L"TUNNEL" },
    {L"Conservatory", L"CONSERVATORY" },
    {L"Lost & Found", L"LOST & FOUND" },
    {L"Closed Exhibit", L"CLOSED EXHIBIT" },

    // Outer Rooms
    {L"Toolshed", L"TOOLSHED" },
    {L"Shelter", L"BOMB SHELTER" },
    {L"Schoolhouse", L"SCHOOLHOUSE" },
    {L"Shrine", L"SHRINE" },
    {L"Root Cellar", L"ROOT CELLAR" },
    {L"Hovel", L"HOVEL" },
    {L"Trading post", L"TRADING POST" },
    {L"Tomb", L"TOMB" },

	// Upgrades (sorted by wiki order, which is alphabetical by base room name)
    {L"Electric Eel Aquarium", L"AQUARIUM (electric eel)" },
    {L"Goldfish Aquarium", L"AQUARIUM (golfish)" },
    {L"Starfish Aquarium", L"AQUARIUM (starfish)" },
    {L"Break Room", L"BREAK ROOM" },
    {L"Speakeasy", L"SPEAKEASY" },
    {L"Pool Hall", L"POOL HALL" },
    {L"Boudoir (obs)", L"BOUDOIR (obs)" }, // TODO: WTF
    {L"Boudoir (par)", L"BOUDOIR (par)" }, // TODO: WTF
    {L"Boudoir (walk)", L"BOUDOIR (walk)" }, // TODO: WTF
    {L"Bunk Room (gems)", L"BUNK ROOM gems" },
    {L"Bunk Room (coins)", L"BUNK ROOM coins" },
    {L"Bunk Room (keys)", L"BUNK ROOM keys" },
    {L"Cloister of Rynna", L"CLOISTER OF RYNNA" },
    {L"Cloister of Joya", L"CLOISTER OF JOYA" },
    {L"Cloister of Dauja", L"CLOISTER OF DAUJA" },
    {L"Cloister of Veia", L"CLOISTER OF VEIA" },
    {L"Cloister of Mila", L"CLOISTER OF MILA" },
    {L"Cloister of Lydia", L"CLOISTER OF LYDIA" },
    {L"Cloister of Orinda", L"CLOISTER OF ORINDA" },
    {L"Cloister of Draxus", L"CLOISTER OF DRAXUS" },
    {L"Hallway Closet", L"HALLWAY CLOSET" },
    {L"Bedroom Closet", L"BEDROOM CLOSET" },
    {L"Empty Closet", L"EMPTY CLOSET" },
    {L"Corriyard", L"COURTYARD (corriyard)" },
    {L"Courtyard (digs)", L"COURTYARD (digs)" },
    {L"Courtyard (gems)", L"COURTYARD (gems)" },
    {L"Geist Bedroom", L"GEIST BEDROOM" },
    {L"Guess Bedroom", L"GUESS BEDROOM" },
    {L"Quest Bedroom", L"QUEST BEDROOM" },
    {L"Hallway (key)", L"HALLWAY (1key)" },
    {L"Hallway (trunk)", L"HALLWAY (1trunk)" },
    {L"Hallway (tomorrow)", L"HALLWAY (Tomorrow)" },
    {L"Mail Room (freight)", L"MAIL ROOM (freight)" },
    {L"Mail Room (no contact)", L"MAIL ROOM (nocontact)" },
    {L"Mail Room (same day)", L"MAIL ROOM (sameday)" },
    {L"Nook (2 keys)", L"NOOK (2keys)" },
    {L"Breakfast Nook", L"BREAKFAST NOOK" },
    {L"Reading Nook", L"READING NOOK" },
    {L"Nursery (steps)", L"NURSERY10" },
    {L"Nurse's Station", L"NURSES STATION" },
    {L"Indoor Nursery", L"INDOOR NURSERY" },
    {L"Parlor (3 gems)", L"PARLOR (3gems)" },
    {L"Parlor (2 keys)", L"PARLOR (windup)" },
    {L"Funeral Parlor", L"FUNERAL PARLOR" },
    {L"Storeroom (2 gems)", L"STOREROOM (gems)" },
    {L"Storeroom (10 coins)", L"STOREROOM (coins)" },
    {L"Storeroom (2 keys)", L"STOREROOM (keys)" },
    {L"Spare Bedroom", L"SPARE BEDROOM" },
    {L"Her Ladyship's Spare Room", L"HER LADYSHIP'S SPARE ROOM" },
    {L"Servant's Spare Quarters", L"SERVANT'S SPARE QUARTERS" },
    {L"Spare Master Bedroom", L"SPARE MASTER BEDROOM" },
    {L"Spare Greenroom", L"SPARE GREENROOM" },
    {L"Spare Patio", L"SPARE PATIO" },
    {L"Spare Terrace", L"SPARE TERRACE" },
    {L"Spare Veranda", L"SPARE VERANDA" },
    {L"Spare Hall", L"SPARE HALL" },
    {L"Spare Foyer", L"SPARE FOYER" },
    {L"Spare Great Hall", L"SPARE GREAT HALL" },
    {L"Spare Secret Passage", L"SPARE SECRET PASSAGE" },
};